defaults: &defaults
  work_accept:
    url: https://komo-service-staging.herokuapp.com/staff/working_hours/%s/edit
    mail_from: tsuna.tonight@gmail.com
  apply_for_authentication:
    url: https://komo-service-staging.herokuapp.com/admin/users/%s/edit
    mail_from: tsuna.tonight@gmail.com
    mail_to: tsuna.tonight@gmail.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  work_accept:
    url: https://komo-service-staging.herokuapp.com/staff/working_hours/%s/edit
    mail_from: leetanshim@gmail.com
  apply_for_authentication:
    url: https://komo-service-staging.herokuapp.com/admin/users/%s/edit
    mail_from: leetanshim@gmail.com
    mail_to: leetanshim@gmail.com
